### ISSUE TITLE
Avoid censorship via reddit

### ISSUE THREAD

**Issue by gterzian** [emberian/this-week-in-rust#1145]
That's disappointing. 

So you don't want to include articles that "reddit" disagrees with? I actually never look at comments on reddit anymore, because of the overall low quality of discussions I used to see when I did look. I will not change this very good habbit now. 

Do you have any guidelines on your criteria for publishing? Anywhere I can appeal? If you're going to refuse an article based on reddit, you're going in the wrong direction. I would suggest a more robust procedure, like peer review, or anything else that doesn't amount to a popularity contest or the dictatorship of the majority.

You've published a ton of articles by me before, so it would be surprising if this article suddenly represented "misinformation". If anything, reddit is a potent source of misinformation.

if someone disagrees with what I write, I'll be happy to read their long-form rebuttal. However I will not pay attentions to comments, or votes, on a platform like reddit which is an accurate measurement only of the lunacy of crowds. And neither should you. 

_Originally posted by @gterzian in https://github.com/emberian/this-week-in-rust/pull/1140#issuecomment-585662039_

**Comment by nasa42** [comment]
I'm sorry you feel this way. I don't consider myself to be an expert in Rust and as such I take reviews from others (e.g., comments on reddit) into account when selecting articles to include. It is not possible to include every article, and I must apply some criteria to filter them, and so far, I've found ratio of reddit upvotes/downvotes and comments to be a good metric.

I'm open to suggestions on how I can make the process of selecting articles better.

> if someone disagrees with what I write, I'll be happy to read their long-form rebuttal.
> However I will not pay attentions to comments, or votes, on a platform like reddit...

If you're open to feedback, you'd find the top comment [on reddit thread](https://www.reddit.com/r/rust/comments/ezq09a/further_thoughts_on_asyncawait/) helpful.

I'm not defending reddit and sometimes it gets ugly but I wouldn't suggest that you discount it altogether.

> Anywhere I can appeal?

TWiR is an official Rust Community project and you can write to the community team mailing list. https://www.rust-lang.org/governance/teams/community
I'm not an expert in Rust and it is very possible that I've misjudged here and I'm happy to include the article in next TWiR issue if the Community team thinks so.

**Comment by gterzian** [comment]
Also, giving votes or discussions on reddit any editorial weight, seems counter to a previously made decision to remove links to reddit: see https://github.com/emberian/this-week-in-rust/issues/709

It's one thing to direct readers there for additional discussion(and a good thing to not do it anymore), it's entirely another to have the discussions or votes there decide which article should be allowed to be posted in the first place. 

cc @wycats @nikomatsakis

**Comment by gterzian** [comment]
I have looked at the top comment reddit, there is nothing there that makes my article somehow "misinformation". I anything, different perspectives on async/await are sorely needed.

**Comment by gterzian** [comment]
Ok, I will write an email to the community team as you suggest.

**Comment by nasa42** [comment]
As discussed in the mailing list, I'd include the article in next week's issue (as this week's issue is already published).

We still however need to come with a formal guidelines on how articles should be selected. Let's discuss that in https://github.com/emberian/this-week-in-rust/pull/1015.
