### ISSUE TITLE
Rust-NYC event was not included

### ISSUE THREAD

**Issue by remram44** [emberian/this-week-in-rust#1150]
Is there anything to do to get a meetup listed in TWiR, in addition to adding it to the [community calendar](https://www.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)? The NYC event was not included, despite being in there with a link.

Just wondering if I did this wrong or missed some step :no_mouth:

**Comment by nasa42** [comment]
There are no additional requirements. I collect events from the community calendar and seems like I missed it by accident, sorry.
You can always make a PR and that way it will harder for be me to miss. :smile:
