### ISSUE TITLE
Date chaos?

### ISSUE THREAD

**Issue by therealprof** [emberian/this-week-in-rust#1157]
The latest post scheduled for 2020-02-28 according to the filename but was posted on 2020-02-18. While this weeks draft (scheduled for today) still has the same content als last weeks post?

Where do I put new entries now? 😅

Note to self: https://tech.olx.com/presenting-dali-an-image-processor-service-514e6be00de8

**Comment by nasa42** [comment]
You are correct, I've fixed the date now. I'll manually add the article in today's issue.
