### ISSUE TITLE
Looking for a new lead maintainer.

### ISSUE THREAD

**Issue by nasa42** [emberian/this-week-in-rust#1167]
If you are interested in becoming lead maintainer of TWiR, please fill this form:

https://docs.google.com/forms/d/e/1FAIpQLScJUYdkpLwQc_4zn3oxpVLdT3IHtKlYEBAzd6lgSgE3vsTOtA/viewform

----

I'm [retiring from TWiR](https://blog.rust-lang.org/inside-rust/2020/03/13/twir-new-lead.html) and TWiR is looking for a new lead maintainer. If you're interested and/or if you've questions, please respond below. If you'd like to contact me privately, please use the email on my GitHub profile.

My weekly routine:

(On average I spend about 4-6 hours/week on TWiR).

* Scout through reddit for posts to add in "News & Blog Posts" section (this is usually what takes majority of the time).
* Merge recently opened PRs.
* Go through Twitter mentions and add content if requested.
* Check email for any direct emails (search for `rust` and `twir`).
* Check reddit inbox.
* Fill-in other sections, e.g., RFC and calendar. (I could and should have automated it to some extent, but it is one of those things that I kept deferring to _this weekend_, and 5 years later, here we are).
* Generate the static pages using `pelican --delete-output-directory content`.
* Run the web-server locally and verify contents. (`cd output; python3 -m http.server`).
* Copy static pages to the [GitHub Pages](https://github.com/this-week-in-rust/this-week-in-rust.github.io) repository (`rsync -razvP --delete --exclude /CNAME --exclude /.git output/ /path/to/this-week-in-rust.github.io/`).
* Commit and push [GitHub Pages](https://github.com/this-week-in-rust/this-week-in-rust.github.io) repo.
* Publish to both reddit and Twitter. (I'll give access to the Twitter account).
* Create draft article for next week.
* Add reddit link in the footer of current post.
* Commit and push.
* Wait for about 24 hours (in case community finds any issue in the post).
* Send the newsletter through Mailchimp. (I'll give access to Mailchimp).
  * `TWIR_NEWSLETTER_THEME=1 pelican --delete-output-directory content` to generate HTML.
  * Start the server (`cd output; python3 -m http.server`) and copy HTML to `/tmp/in.html`.
  * Generate email-friendly HTML (`juice --web-resources-images false /tmp/in.html /tmp/out.html`).
  * Create a new campaign in Mailchimp, copy the HTML, and send the newsletter.

**Comment by djc** [comment]
Can you elaborate a bit more on the activities of the lead maintainer compared to the other maintainers? How much time per week do you generally spend?

**Comment by gbutler69** [comment]
I have read every issue (as well as back issue) of TWIR since I discovered "Rust" and I consider it an essential and valuable resource. Though I haven't yet participated fully in Rust development and the Rust community, I believe I could make the necessary time to maintain TWIR and would be willing to throw my hat in the ring to ensure that this valuable resource, that the maintainers to now have to diligently and effectively shepherded, continues to exist for both newcomers and veterans of Rust. Generally speaking, how many hours a week (and when) is usually required for this?

**Comment by Lucretiel** [comment]
Can you talk about the responsibilities of a maintainer? Are they doing content discovered & curation or more infrastructure site work? Or both?

**Comment by ecton** [comment]
I'm new to the community and Rust in general. I'm currently exploring game dev in Rust, but I'm almost certain that my next commercial project will feature Rust in it. However, I have been loving This Week in Rust because it always highlighted great content that I knew was worth reading through. So I'm also joining gbutler69 in thanking you for your contributions!

I'd love to also put my name in the proverbial hat as well.

Thanks again for this wonderful resource!

**Comment by sezna** [comment]
I’ve been working with Rust since ~2015 and currently work in it every day for my job. I’ve been an avid subscriber of TWiR as well, and am grateful for the impact it has had on increasing visibility and bringing the community closer together. Thank you @nasa42!

I will throw my hat in as well. I also echo the above curiosity about how much of it is curation/content discovery vs. just writing.

**Comment by hmble** [comment]
I would also like to contribute to this in any way possible. I am excited to see so many people excited to keep TWiR get going. @nasa42 can you elaborate more on 
1. How where we can submit collected articles ?
2. Which issues should we include in current blogs **Updates from Rust core** ?

Also I would love to find a way so that many of us can work together on this. 

BTW Thanks a lot for your work contribution @nasa42

**Comment by louy2** [comment]
TWiR has been the greatest joy I have each week, on par with morning papers. Thank you so much for your work!

Also curious about how the work is done behind the scenes. Specifically:

1. How are the posts collected? RSS of blogs? Reddit? Hackernews?
2. Which posts go in? Editorial decision? Upvotes? Category balance?
3. Any tools needed? Summary bot? Auto-tagger? Upvote dashboard?

**Comment by donnellycolton** [comment]
I'd love to be considered as the new maintainer. I've been working in Rust for the last year or so, and TWIR has been one of the most useful tools for learning new parts about the language and its ecosystem.

Thank you so much @nasa42 for your diligence, your work has been wonderful

**Comment by lukekhamilton** [comment]
Hey guys, 
I am still somewhat new to rust however I would love to be of help in whatever way makes sense. With my limited experience, I would love to work/support someone thats also more experienced and this could be a great way for me to get more involved. 
Thanks <3

**Comment by llogiq** [comment]
For the record, I'll continue writing up the Crate and Quote of the week and the notable core changes. We may also opt to further split the workload (and we did so in the past), however there must be one person who pulls all contributions together, sends out the newsletter & pushes the site update.

**Comment by llogiq** [comment]
Regarding tools needed, a script to collect RFCs in FCP / merged could be helpful (as we don't make a selection in that section). I am unsure if @nasa42 already has something in place. The other sections require manual editing.

**Comment by yaahc** [comment]
I'd be happy to help out, particularly with the call for participation section.

**Comment by nasa42** [comment]
I'm quite overwhelmed with all the responses, thank you everyone!

I've updated the description of this issue with my weekly routine.

Because all sections are quite independent, it is very possible to divide the work between multiple people. However, we still need someone to take the lead, coordinate with others, and publish the article.

I'd like to ask everyone if they are interested in the leadership role or if they'd like to contribute to just a specific section. 

@llogiq handles "Crate of the Week", "Quote of the Week", and Notable Changes in Rust Core. That leaves us with:

* Leadership (publication & coordination).
* News & Blog Posts (in my personal experience, this section takes most times & effort).
* Call for Participation (@yaahc has shown interest).
* Approved & New RFCs
* Upcoming Events
* Rust Jobs

Please respond with which responsibilities you'd like to pick.

Also happy to accept PRs to automate last 3 sections.

Answering questions:

> Can you elaborate a bit more on the activities of the lead maintainer compared to the other maintainers?

Lead is about taking the responsibility of publishing post and newsletter. They may also need to write sections if other contributors failed to deliver by deadline.

> Can you talk about the responsibilities of a maintainer? Are they doing content discovered & curation or more infrastructure site work? Or both?

About infrastructure: We use GitHub Pages for blog and Mailchimp for newsletter. Both are pretty much maintenance free.

> How much time per week do you generally spend?

Usually about 4-6 hours/week.

> How where we can submit collected articles ?

A PR is the best way to do so.

> How are the posts collected? RSS of blogs? Reddit? Hackernews?

I've been using Reddit and Twitter mentions for sources.

> Which issues should we include in current blogs Updates from Rust core ?
> Which posts go in? Editorial decision? Upvotes? Category balance?

Mostly editorial decision. See https://github.com/emberian/this-week-in-rust/issues/1145 and https://github.com/emberian/this-week-in-rust/pull/1015 for more info.

> Any tools needed? Summary bot? Auto-tagger? Upvote dashboard?

As of now, we use [Pelican](https://github.com/getpelican/pelican) as our static-site generator. And [Juice](https://github.com/Automattic/juice) for inlining CSS for newsletter emails. I'd leave it to new maintainers on how they'd like to evolve TWiR.

**Comment by donnellycolton** [comment]
I'd be happy to work on the news/blog posts (therefore sacrificing my Reddit, Twitter, and email inboxes)

**Comment by sezna** [comment]
I’d be happy to tackle the RFCs task. First manually, eventually less so. 😄

**Comment by yaahc** [comment]
> Also happy to accept PRs to automate last 3 sections.

Sounds like a great issue for the CFP section :eyes:

**Comment by llogiq** [comment]
@sezna I'll note that automating the PR fetching isn't that hard; but it will still require some manual scrubbing to fix the titles for letter case and markdown correctness.

Also I think the "jobs" section basically writes itself with PRs from various parties.

**Comment by rickprice** [comment]
Hi, I would like to help as well.

**Comment by sezna** [comment]
I'll throw my hat in for the leadership role and whatever duties remain undistributed to volunteers. Having scanned the waters of the previous task I'd volunteered for (PR fetching), I don't think it enough to justify an entirely separate position, and I could roll it in with synchronizing all the contributions.

**Comment by abreis** [comment]
@cdmistman if you can track each week's News & Blog Posts somewhere public, something low-friction like hackmd or dropbox paper, I can help fill in the gaps. Having to open a PR to add a new article is a bit too much, though.

**Comment by cdmistman** [comment]
@abreis I agree, PR's for such a large list is a lot, but since most of the list will often be pushed by (possibly) me via Twitter/Reddit mentions and (possibly) email, I think it'd be fine to leave the current PR system as it is, so that trolls can't just keep deleting whatever is in the public file. If there are gaps, then any of the merge-access contributors should be able to quickly audit and merge before publishing the next issue

**Comment by srikwit** [comment]
@nasa42 I would also like to help out.

**Comment by pkrasam** [comment]
@nasa42 Thank You mate, I love reading TWiR every week

This is brilliant and amazing -- here I was thinking, there won't be too many ppl willing to assist with such a task and I am pleasantly surprised we have such an awesome community.

I would also like to put up my hand to **lead and assist** with maintaining `TWiR`.

@nasa42 given we have so many able and willing ppl to help out, may I suggest we pull a final-list of ppl and give each one of them a sub-task, plus if more than 1 person wants to be a lead, may be we do a round-robin.

I have pulled a list of high-level topics from our newsletter -- should we use this as a starting point for ppl to self-nominate themselves as maintainers?

**TWiR**
- Updates from Rust Community
- Crate of the Week
- Call for Participation
- Updates from Rust Core
- Upcoming Events
- Rust Jobs
- Quote of the Week

Cc: @srikwit @cdmistman @abreis @sezna @rickprice @yaahc @lukekhamilton @louy2 @hmble @ecton @gbutler69 @djc and anyone else I might missed out

**Comment by srikwit** [comment]
@pkrasam I can contribute for "Updates from Rust Community", "Crate of the Week" and "Rust Jobs".

**Comment by nellshamrell** [comment]
I am happy to help as well! I can contribute to "Updates from Rust Community", "Updates from Rust Core", and "Call for Participation".

**Comment by yaahc** [comment]
re my [earlier comment](https://github.com/emberian/this-week-in-rust/issues/1167#issuecomment-599128175) I'm interested in helping with the `Call for Participation` section.

**Comment by cdmistman** [comment]
I think it's best to wait until @nasa42 has picked replacement leader(s) before deciding on structure

**Comment by pkrasam** [comment]
Thanks @srikwit @nellshamrell @yaahc @cdmistman

**Comment by llogiq** [comment]
@pkrasam @srikwit Please note that I plan on continuing doing Crate + Quote of the Week and Notable Core Changes for the foreseeable future.

**Comment by louy2** [comment]
I can contribute to "Updates from Rust Community"

**Comment by lukekhamilton** [comment]
I'd be up for doing the Rust Jobs section and coordinating that.

**Comment by nasa42** [comment]
Thank you everyone for your responses!

I'm happy to see a lot of people volunteering to support individual sections of the newsletter, and if coordinated right, it can be a great team experience! However, I'm wary of a large team size as I feel that larger the team, the more administrative overhead it is for the lead maintainer, specially for TWiR which has weekly deadlines. E.g., coordinating with multiple individuals to make PRs before deadlines for tasks that would just take a few minutes to fill-in by self. I'm not saying this to discourage future contributors, just that I'd prefer to keep the team size smaller and distribute more tasks among them.

My primary concern is the "News & Blog Posts" section, which requires some content curation & editorial skills (and I'm not a good example of that, btw). In my experience, the hardest part has been saying "no" to some PRs and requests to include an article ([some examples](https://github.com/emberian/this-week-in-rust/pulls?q=%22good+fit%22), see also: #1015), so I expect new editor(s) to be prepared for that.

To help us decide the next lead maintainer, I've created a Google Form to gather more information and I request everyone who is interested to fill this form. The responses will be shared with the Rust Community team.

https://docs.google.com/forms/d/e/1FAIpQLScJUYdkpLwQc_4zn3oxpVLdT3IHtKlYEBAzd6lgSgE3vsTOtA/viewform

Once again, thank you everyone for your interest!
