### ISSUE TITLE
Switch to only promoting online meetups

### ISSUE THREAD

**Issue by gilescope** [emberian/this-week-in-rust#1169]
Given the current pandemic, can we only promote virtual meetups in the meetups list? Maybe announce the change a week before implementing? (And maybe we change the format to time/country and language as I guess they could be more inclusive as you don’t need to be physically present)

**Comment by nasa42** [comment]
I'd let event organisers and attendees make their own decisions based on their local situations.
Also, we do include online events when available (at the top of the list).
