### ISSUE TITLE
I'd like to start a "This Week in Rust" podcast

### ISSUE THREAD

**Issue by nellshamrell** [emberian/this-week-in-rust#1195]
Hello there!

I'd like to start a "This week in Rust" podcast that dives a little deeper and provides context around a few of the stories in each episode. I would pre-record at least the first few episodes (posting them after a bit of editing) until I get a format developed, then would likely move to broadcasting them live while I record on Twitch and YouTube. Would you have any objections to me moving forward with this? The initial goal would be to get a 20-30 min episode up within two days of the newsletter hitting people's inboxes (maybe eventually the same day).

Some background on me: I am a Sr. Staff Engineer at Mozilla who works full time on the Rust team. I currently am a co-host of the [Adventures in DevOps](https://devchat.tv/adventures-in-devops/) podcast and, previously, the [Food Fight](http://foodfightshow.org/) podcast.

**Comment by nasa42** [comment]
This is fantastic! Thank you for taking the initiative!
I'll close this issue and get in touch with you over email.
