### ISSUE TITLE
duplicate article link in 2020 05 19 version

### ISSUE THREAD

**Issue by programmerjake** [emberian/this-week-in-rust#1257]
the `Taking Advantage of Auto-Vectorization in Rust` article appears twice.

https://github.com/emberian/this-week-in-rust/blob/dd4b4d1c96205cf21e12c5cc0d92ee62e453855a/content/2020-05-19-this-week-in-rust.md#L23-L31

**Comment by hmble** [comment]
Just to add my opinion I created a issue #1222 so that new contributors can check if a link to blog post was already included in previous TWiR.
