### ISSUE TITLE
Missing news and blog posts in issue 344

### ISSUE THREAD

**Issue by vosshall** [emberian/this-week-in-rust#1325]
Looks like they were moved to issue 345 in 03b8741d903bf774b7078c4dec94333ea30edabb?

**Comment by vosshall** [comment]
It's fine on the blog but is missing in the email edition.

![twir344](https://user-images.githubusercontent.com/46854537/85638748-96599380-b63b-11ea-81b7-2f0053bcc0fd.jpg)

**Comment by nellshamrell** [comment]
Yep, something went wrong there. Fixing and re-sending the newsletter with that section filled in.

**Comment by nellshamrell** [comment]
Ah - looks like I deleted the links in the wrong file when setting up the draft for 345. Apologies!

**Comment by nellshamrell** [comment]
Just queued up a new email to go out to the list with the missing sections filled in! Thanks for bringing this to my attention!
