### ISSUE TITLE
Show Rust blog posts separately

### ISSUE THREAD

**Issue by camsteffen** [emberian/this-week-in-rust#1327]
It would be nice if official Rust blog posts were some how visually distinct. These are generally the items I am most interested in reading. Here's a couple ideas:

### Use the rust icon as a bullet

<img width="378" alt="image" src="https://user-images.githubusercontent.com/5565418/85873992-8d7dd480-b797-11ea-8d71-6fb0928841fb.png">

### Create a different section

<img width="369" alt="image" src="https://user-images.githubusercontent.com/5565418/85874280-febd8780-b797-11ea-8714-d27d4bcc300d.png">

**Comment by nellshamrell** [comment]
This is very doable and I'm on board with this. @llogiq and @cdmistman - I'm curious what you two think?

**Comment by cdmistman** [comment]
I myself was thinking about this yesterday. I think it might be nice to have subsections within the news and blog posts section itself, something like this:

```markdown
## News and Blog Posts

### Official Rust

- Announcing Rust 1.44.1

### WASM

- Some article on WASM
- [video] Some video on WASM

### etc
```

Could look a bit cluttered, but i do like the separation from the rust blog from the rest of the news and blog posts. I've been trying to make sure that the rust blog links are at the top of the section when making my PR's, but the differentiation would help those trying to focus only on those

**Comment by nellshamrell** [comment]
That sounds good. I think the headings might depend on what content we have in that week (i.e. if we happen to get a bunch of content on WASM, we have that all under a WASM heading. If we get one piece of content related to WASM....we may not have the heading that week)

**Comment by nellshamrell** [comment]
We've implemented the first iteration of these headings, so I am closing this issue :)
