### ISSUE TITLE
Job Posting

### ISSUE THREAD

**Issue by mcichosz** [emberian/this-week-in-rust#1337]
Hi There!

I was wondering if its possible to add our job into the newsletter? We are hiring multiple Rust Developers @ 1Password. Here is the link: https://jobs.lever.co/1password/0623888f-0125-41b9-9902-eae8cfeae0c3

Thanks!
Margaret

**Comment by mcichosz** [comment]
Hii - just wondering if there's any follow up to this?

**Comment by nellshamrell** [comment]
I added this into this week's newsletter which is being published today!
