### ISSUE TITLE
TWIR 350 has a repeated entry

### ISSUE THREAD

**Issue by CGMossa** [emberian/this-week-in-rust#1431]
The
- [Prevent Breaking Code Changes in Future Releases using non exhaustive enums in Rust](https://medium.com/@knoldus/prevent-breaking-code-changes-in-future-releases-using-non-exhaustive-enums-in-rust-ace1ac4650d9)

Appears twice, but with two different links: [Second link](https://blog.knoldus.com/prevent-breaking-code-changes-in-future-releases-using-non-exhaustive-enums-in-rust/)

**Comment by nellshamrell** [comment]
Thank you! This has been fixed with #1433
