### ISSUE TITLE
RSS feed lies about last update time

### ISSUE THREAD

**Issue by pravic** [emberian/this-week-in-rust#649]
Git: 8e9434c (May 30)

Website:

> HEAD https://this-week-in-rust.org
Last-Modified: Wed, 30 May 2018 17:09:21 GMT

Atom feed:

> HEAD https://this-week-in-rust.org/atom.xml
Last-Modified: Wed, **30 May 2018 17:09:20** GMT
&lt;updated>**2018-05-29T00:00:00-04:00**&lt;/updated>&lt;entry>&lt;title>This Week in Rust 236</title>

RSS feed:

> HEAD https://this-week-in-rust.org/rss.xml
Last-Modified: Wed, 30 May 2018 17:09:20 GMT
&lt;lastBuildDate>Tue, **29 May 2018 00:00:00** -0400&lt;/lastBuildDate>&lt;item>&lt;title>This Week in Rust 236</title>

**Comment by nellshamrell** [comment]
Closing due to the age of this issue, but if there are any updates to it please feel free to re-open.
